// General
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const SET_ERROR = 'SET_ERROR';

// Auth
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UNSET_CURRENT_USER = 'UNSET_CURRENT_USER';
export const START_CHECK_USER_AUTHENTICATION =
  'START_CHECK_USER_AUTHENTICATION';
export const END_CHECK_USER_AUTHENTICATION = 'END_CHECK_USER_AUTHENTICATION';
